//-----------------------------------------------------------------------
// <copyright file="EnumeratePoolStatesResponse.cs" company="Microsoft">
//     Copyright (c) Microsoft. All rights reserved.
//     Internal use only.
// </copyright>
// <auto-generated /> 
//-----------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Commands.Utilities.CloudGame.Contract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class EnumerateClustersResponse
    {
        [DataMember(Name = "clustersInfo")]
        public List<ClusterInformationEx> ClusterInformationCollection { get; set; }
    }

    /// <summary>
    /// The extended cluster information that gives the VM package and game mode names in addition to base class information
    /// </summary>
    [DataContract(Namespace = "")]
    public class ClusterInformationEx : ClusterInformation
    {
        /// <summary>
        /// Gets or sets the name of the VM package.
        /// </summary>
        [DataMember(Name = "gsiName")]
        public string VmPackageName { get; set; }

        /// <summary>
        /// Gets or sets the name of the game mode.
        /// </summary>
        [DataMember(Name = "variantName")]
        public string GameModeName { get; set; }
    }

    /// <summary>
    /// The cluster information response contract for gsms.
    /// </summary>
    [DataContract]
    public class ClusterInformation
    {
        /// <summary>
        /// Gets or sets the cluster Id.
        /// </summary>
        [DataMember(Name = "clusterId")]
        public string ClusterId { get; set; }

        /// <summary>
        /// Gets or sets the session Id.
        /// </summary>
        [DataMember(Name = "sessionId")]
        public string SessionId { get; set; }

        /// <summary>
        /// Gets or sets the game mode Id.
        /// </summary>
        [DataMember(Name = "variantId")]
        public string GameModeId { get; set; }

        /// <summary>
        /// Gets or sets the VM package Id.
        /// </summary>
        [DataMember(Name = "gsiId")]
        public string VmPackageId { get; set; }

        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        [DataMember(Name = "state")]
        public string State { get; set; }

        /// <summary>
        /// Gets or sets the location.
        /// </summary>
        [DataMember(Name = "location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or sets the location.
        /// </summary>
        [DataMember(Name = "machineResidence")]
        public string MachineResidence { get; set; }

        /// <summary>
        /// Gets or sets the timestamp at which the state transition happened.
        /// </summary>
        [DataMember(Name = "transitionTimestampUtc")]
        public string TransitionTimestampUtc { get; set; }
    }
}
